version: '3.1'

services:

  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5436:5432"
    environment:
      POSTGRES_PASSWORD: postgres123
    volumes:
      - ./data:/var/lib/postgresql/data
